// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import { Raleway } from 'next/font/google';
// import './globals.css';
// import Navigation from '@/components/shared/Navigation';
// import Footer from '@/components/shared/Footer';
// import { useRouter } from 'next/navigation';

// const inter = Inter({ subsets: ['latin'] });
// const raleway = Raleway({ weight: ['500', '700'], subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const router = useRouter();

//   // Function to determine background color based on route
//   const getBackgroundColor = () => {
//     switch (window.location.pathname) {
//       case '/courses':
//         return 'bg-[#8BD5FF80]';

//       default:
//         return 'bg-[#FEF7F7]';
//     }
//   };
//   const background = getBackgroundColor();
//   return (
//     <html lang="en">
//       <body className={raleway.className}>
//         <div
//           className={`${background} bg-[#FEF7F7] transition-all px-2 lg:px-12 lg:py-2 relative overflow-x-hidden h-full w-full`}
//         >
//           <Navigation />
//           <div>{children}</div>
//         </div>
//         <Footer />
//       </body>
//     </html>
//   );
// }

// RootLayout.jsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Raleway } from 'next/font/google';
import { ReactNode, useEffect, useState } from 'react';
import './globals.css';
// import '~slick-carousel/slick/slick.css';
// import '~slick-carousel/slick/slick-theme.css';
import Navigation from '@/components/shared/Navigation';
import Footer from '@/components/shared/Footer';
import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });
const raleway = Raleway({ weight: ['500', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const background = 'bg-[#FEF7F7]';
  return (
    <html lang="en">
      <body className={raleway.className}>
        <div
          className={`${background} px-2 lg:px-12 lg:py-2 relative overflow-x-hidden h-full w-full`}
        >
          <Navigation />
          <div>{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
