import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Raleway } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/shared/Navigation';
import Footer from '@/components/shared/Footer';

const inter = Inter({ subsets: ['latin'] });
const raleway = Raleway({ weight: ['500', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <div className="bg-[#FEF7F7] relative overflow-x-hidden h-full w-full">
          <Navigation />
          <div className="px-2 lg:px-12 lg:py-2">
            <div>{children}</div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
